# Generated by Django 4.1.7 on 2023-03-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
