# Generated by Django 4.1.7 on 2023-03-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_candidate_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='situation',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Pending', max_length=100, null=True),
        ),
    ]
