# Generated by Django 4.1.7 on 2023-03-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_candidate_situation'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='created_add',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
