# Generated by Django 4.1.7 on 2023-03-27 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_candidate_created_add'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='created_add',
            new_name='created_at',
        ),
    ]
